services:
    influxdb:
        image: influxdb
        ports:
            - 8096:8086
        volumes:
            - influxdata:/var/lib/influxdb
        networks:
            - chinspector
    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
        volumes:
            - grfdata:/var/lib/grafana
            - grfconf:/etc/grafana
            - grflog:/var/log/grafana
        networks:
            - chinspector

volumes:
    influxdata: {}
    grfdata: {}
    grfconf: {}
    grflog: {}

networks:
    chinspector: {}